name: Build & Release

on:
  - push

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.7.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm ci
      - run: npm run lint
      - run: npm test -- --run --coverage
      - run: npm run typecheck -- --run
      - run: npm run build

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.7.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm ci
  #     - run: npm run semantic-release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
